[tool.poetry]
name = "violetear"
version = "0.4.1"
description = "A minimalist CSS generator"
authors = ["Alejandro Piad <apiad@apiad.net>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
mkdocs = "^1.3.1"
mkdocs-material = "^8.4.0"
pytest = "^7.1.2"
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
